### ISSUE TITLE
Marker Map 의존성 문제.

### ISSUE THREAD

**Issue by cooldplay** [NewsJelly/jelly-chart#1]
마침 marker map 유형 필요해서 젤리차트를 써보려고 했으나...
1차로
```javascript
Uncaught ReferenceError: daum is not defined
```
카카오 맵 sdk 를 필요로 하기에 직접 sdk 를 로드한 다음, 샘플 코드를 넣고 다시 확인해 봤더니 render 단계에 문제가 발생합니다.

```javascript
kakao.js:3 Error: <ellipse> attribute cx: Expected length, "NaN".
Yb @ kakao.js:3
ob.bd @ kakao.js:68
c.v @ kakao.js:140
c.U @ kakao.js:140
c.z @ kakao.js:128
target.forEach.d @ _mark.js:61
__nodes @ _mark.js:45
callback @ _mark.js:109
(anonymous) @ _mark.js:116
_mark @ _mark.js:98
process.forEach.p @ render.js:16
run @ render.js:12
render @ render.js:44
...생략
```

확인 한번 해주세요.

**Comment by wonderino** [comment]
현재 Marker-map 사용을 위해서는 

`html` 상에

 `<script type="text/javascript" src="//apis.daum.net/maps/maps3.js?apikey=[YOUR_APIKEY]&libraries=services"></script>`

같은 형태로 스크립트를 별도로 로딩 해야합니다.
